# Generated by Django 5.0.6 on 2024-06-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='descript',
            field=models.TextField(blank=True, null=True),
        ),
    ]
