# Generated by Django 5.0.6 on 2024-06-14 05:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_review_descript'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.PositiveIntegerField(default=5, null=True, validators=[django.core.validators.MinValueValidator, django.core.validators.MaxValueValidator]),
        ),
    ]
